services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: prefect
      POSTGRES_PASSWORD: prefect
      POSTGRES_DB: climate_db
    ports:
      - "5432:5432"
    volumes:
      - ./init_db.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U prefect -d climate_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  prefect:
    build: .                     # Собираем из Dockerfile
    command: >
      bash -c "
        export PREFECT_API_SERVICES_FLOW_RUN_NOTIFICATIONS_ENABLED=false &&
        prefect server start --host 0.0.0.0 &
        sleep 10 &&
        python /workspace/flows/etl_flow.py &&
        tail -f /dev/null
      "
    ports:
      - "4200:4200"
    volumes:
      - .:/workspace
    working_dir: /workspace
    environment:
      DB_HOST: postgres
    depends_on:
      postgres:
        condition: service_healthy
        
  dash:
    build: .                    # использует твой Dockerfile с зависимостями
    command: python /workspace/dashboards/app.py
    ports:
      - "8050:8050"             # порт Dash
    volumes:
      - .:/workspace            # монтируем код
    working_dir: /workspace
    environment:
      DB_HOST: postgres         # в Docker-сети БД доступна по имени сервиса
    depends_on:
      - prefect                # ждём, пока ETL завершится